### ISSUE TITLE
Uncaught (in promise) TypeError: createElement is not a function

### ISSUE THREAD

**Issue by milank-developer** [shrpne/vue-inline-svg#53]
Uncaught (in promise) TypeError: createElement is not a function
    at Proxy.render (index.js:24:16)
    at renderComponentRoot (runtime-core.esm-bundler.js:914:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5720:34)
    at ReactiveEffect.run (reactivity.esm-bundler.js:190:25)
    at instance.update (runtime-core.esm-bundler.js:5763:56)
    at callWithErrorHandling (runtime-core.esm-bundler.js:173:36)
    at flushJobs (runtime-core.esm-bundler.js:406:17)

**Comment by nadine-wunu** [comment]
Had the same error, fixed it by installing
`npm install vue-inline-svg@next`
instead of
`npm install vue-inline-svg`

**Comment by shrpne** [comment]
> Had the same error, fixed it by installing `npm install vue-inline-svg@next` instead of `npm install vue-inline-svg`

Thank you! It's correct there are two separate versions of vue-inline-svg for vue2 and for vue3
